-- =====================================================
-- SEED DATA: Skill Library
-- =====================================================

INSERT INTO public.skill_library (category, name, description) VALUES
-- Clinical Skills
('Clinical Skills', 'Physical Examination', 'Systematic evaluation of a patient''s body systems.'),
('Clinical Skills', 'Patient Triage', 'Prioritizing patients based on severity of condition.'),
('Clinical Skills', 'History Taking', 'Gathering relevant medical and lifestyle data from owners.'),
('Clinical Skills', 'Fear-Free Handling', 'Using low-stress techniques to reduce patient anxiety.'),
('Clinical Skills', 'Animal Behavior Assessment', 'Reading body language to predict and manage behavior.'),
('Clinical Skills', 'Basic Restraint', 'Safe holding techniques for standard procedures.'),
('Clinical Skills', 'Advanced Restraint', 'Safe handling for aggressive or high-stress patients.'),
('Clinical Skills', 'Nursing Care', 'Delivering daily medical care and hygiene to inpatients.'),
('Clinical Skills', 'Patient Monitoring', 'Observing and recording vital signs and status changes.'),
('Clinical Skills', 'Pain Scoring', 'Assessing pain levels using validated pain scales.'),
('Clinical Skills', 'Medical Note Accuracy', 'Ensuring records are precise, complete, and legally sound.'),
('Clinical Skills', 'SOAP Documentation', 'Recording Subjective, Objective, Assessment, and Plan data.'),
('Clinical Skills', 'Bandaging Techniques', 'Applying and maintaining therapeutic bandages and splints.'),
('Clinical Skills', 'Wound Care', 'Cleaning, debriding, and managing traumatic or surgical wounds.'),
('Clinical Skills', 'Fluid Therapy', 'Calculating and managing IV and SQ fluid administration.'),
('Clinical Skills', 'Catheter Placement (IV)', 'Aseptic insertion of intravenous catheters.'),
('Clinical Skills', 'Catheter Placement (Urinary)', 'Aseptic insertion of urinary catheters for collection or patency.'),
('Clinical Skills', 'Oxygen Therapy', 'Administering supplemental oxygen via various methods.'),
('Clinical Skills', 'Feeding Tube Placement', 'Placing and managing nasogastric or esophagostomy tubes.'),
('Clinical Skills', 'Nail Trimming', 'Safe trimming of claws without injury to the quick.'),
('Clinical Skills', 'Anal Gland Expression', 'Manual expression of anal sacs.'),
('Clinical Skills', 'Vaccination Protocols', 'Understanding schedules and administration of core vaccines.'),
('Clinical Skills', 'Parasite Prevention Knowledge', 'Knowledge of flea, tick, and heartworm preventatives.'),
('Clinical Skills', 'Common Disease Recognition', 'Identifying signs of frequent veterinary conditions.'),
('Clinical Skills', 'Toxicology Basics', 'Recognizing and initiating treatment for common toxins.'),
('Clinical Skills', 'Post-Operative Monitoring', 'Managing recovery phase immediately after surgery.'),
('Clinical Skills', 'Treatment Sheet Accuracy', 'Correctly logging all treatments given to inpatients.'),

-- Diagnostics & Imaging
('Diagnostics & Imaging', 'Radiology Positioning', 'Positioning patients for clear, diagnostic X-ray images.'),
('Diagnostics & Imaging', 'Radiographic Safety', 'Adhering to PPE and shielding protocols for radiation.'),
('Diagnostics & Imaging', 'Ultrasound Operation', 'Basic handling and setting adjustments of ultrasound machines.'),
('Diagnostics & Imaging', 'Ultrasound Preparation', 'Shaving and prepping patients for abdominal scans.'),
('Diagnostics & Imaging', 'Sample Collection – Blood', 'Venipuncture for CBC/Chem/Lytes analysis.'),
('Diagnostics & Imaging', 'Sample Collection – Urine Cystocentesis', 'Sterile urine collection via needle aspiration.'),
('Diagnostics & Imaging', 'Sample Collection – FNA', 'Fine Needle Aspirate technique for mass sampling.'),
('Diagnostics & Imaging', 'Cytology Preparation', 'Preparing and staining slides for microscopic review.'),
('Diagnostics & Imaging', 'Microscope Use', 'Focusing and navigating slides at various magnifications.'),
('Diagnostics & Imaging', 'Diagnostic Interpretation', 'Analyzing lab results to form a diagnosis.'),
('Diagnostics & Imaging', 'POC Testing', 'Running rapid in-house tests (Parvo, Giardia, etc.).'),
('Diagnostics & Imaging', 'Lab Equipment Operation', 'Maintenance and use of in-house blood analyzers.'),
('Diagnostics & Imaging', 'CBC Reading', 'Interpreting Complete Blood Count data and morphology.'),
('Diagnostics & Imaging', 'Chemistry Panel Interpretation', 'Analyzing organ function markers in blood work.'),
('Diagnostics & Imaging', 'Coagulation Testing', 'Running PT/PTT tests for clotting disorders.'),
('Diagnostics & Imaging', 'Diagnostic Workflow Planning', 'Ordering tests in the most efficient logical sequence.'),
('Diagnostics & Imaging', 'EKG Operation', 'Attaching leads and running electrocardiogram tracings.'),
('Diagnostics & Imaging', 'EKG Interpretation', 'Identifying arrhythmias and normal heart rhythms.'),

-- Surgical & Procedural
('Surgical & Procedural', 'Anesthesia Monitoring', 'Tracking vitals and depth during general anesthesia.'),
('Surgical & Procedural', 'Anesthesia Induction', 'Administering drugs to induce unconsciousness for surgery.'),
('Surgical & Procedural', 'Anesthesia Recovery', 'Managing the patient''s wake-up phase safely.'),
('Surgical & Procedural', 'Aseptic Technique', 'Maintaining sterility to prevent surgical infections.'),
('Surgical & Procedural', 'Surgical Assisting', 'Hands-on assistance to the surgeon during procedures.'),
('Surgical & Procedural', 'Instrument Handling', 'Proper passing and use of surgical tools.'),
('Surgical & Procedural', 'Suturing Assistance', 'Cutting suture and assisting with closure.'),
('Surgical & Procedural', 'Sterile Field Maintenance', 'Preserving the sterile zone during operations.'),
('Surgical & Procedural', 'Dental Prophylaxis', 'Scaling and polishing teeth under anesthesia.'),
('Surgical & Procedural', 'Dental Radiographs', 'Taking diagnostic X-rays of tooth roots.'),
('Surgical & Procedural', 'Dental Charting', 'Mapping oral health and pathology on dental charts.'),
('Surgical & Procedural', 'Intubation', 'Placing endotracheal tube for airway management.'),
('Surgical & Procedural', 'Emergency Intubation', 'Rapid airway access in respiratory arrest scenarios.'),
('Surgical & Procedural', 'Blood Draws (Difficult Veins)', 'Venipuncture on dehydrated or vascularly compromised patients.'),
('Surgical & Procedural', 'IV Catheter Challenges', 'Placing IV access in difficult or blown veins.'),
('Surgical & Procedural', 'Arterial Sampling', 'Collecting blood from arteries for blood gas analysis.'),
('Surgical & Procedural', 'Laser Therapy Use', 'Operating therapeutic laser for pain and healing.'),

-- Emergency & Critical Care
('Emergency & Critical Care', 'Rapid Triage', 'Immediate assessment of life-threatening conditions.'),
('Emergency & Critical Care', 'Shock Protocols', 'Recognizing and treating various stages of shock.'),
('Emergency & Critical Care', 'Crash Cart Management', 'Ensuring emergency drugs and equipment are ready.'),
('Emergency & Critical Care', 'CPR (RECOVER Certified)', 'Basic and Advanced Life Support techniques.'),
('Emergency & Critical Care', 'Fluid Shock Dosing', 'Calculating bolus fluid rates for resuscitation.'),
('Emergency & Critical Care', 'Emergency Drug Knowledge', 'Pharmacology of epinephrine, atropine, and other code drugs.'),
('Emergency & Critical Care', 'Oxygen Cage Setup', 'Preparing and regulating environmental oxygen therapy.'),
('Emergency & Critical Care', 'Ventilation Support', 'Manual or mechanical breathing support for patients.'),
('Emergency & Critical Care', 'ICU Monitoring', 'High-frequency observation of critical status patients.'),
('Emergency & Critical Care', 'Vital Trend Interpretation', 'Noticing subtle degradation in patient stability over time.'),
('Emergency & Critical Care', 'Emergency Communication', 'Clear, closed-loop communication during crisis.'),
('Emergency & Critical Care', 'Toxicity Protocols', 'Specific treatments for chocolate, grapes, xylitol, etc.'),
('Emergency & Critical Care', 'Bite Wound Triage', 'Assessing depth and severity of penetrating trauma.'),
('Emergency & Critical Care', 'GDV Protocol Knowledge', 'Handling suspected bloat/torsion cases rapidly.'),
('Emergency & Critical Care', 'Seizure Management', 'Acute treatment and monitoring of status epilepticus.'),

-- Pharmacy & Treatment
('Pharmacy & Treatment', 'Medication Math', 'Calculating dosages based on weight and concentration.'),
('Pharmacy & Treatment', 'Dose Conversion', 'Converting between mg, ml, and other units.'),
('Pharmacy & Treatment', 'Compounding Basics', 'Mixing medications safely for specific administration needs.'),
('Pharmacy & Treatment', 'Prescription Accuracy', 'Verifying drug, dose, and instructions before dispensing.'),
('Pharmacy & Treatment', 'Controlled Substance Logging', 'Adhering to DEA strict recording requirements.'),
('Pharmacy & Treatment', 'Tablet Splitting Accuracy', 'Precising dividing pills for correct dosing.'),
('Pharmacy & Treatment', 'Liquid Medication Prep', 'Measuring oral suspensions accurately.'),
('Pharmacy & Treatment', 'Injection Technique IM', 'Intramuscular injection administration.'),
('Pharmacy & Treatment', 'Injection Technique SQ', 'Subcutaneous injection administration.'),
('Pharmacy & Treatment', 'Injection Technique IV', 'Direct Intravenous injection administration.'),
('Pharmacy & Treatment', 'Pharmacy Inventory', 'Managing stock levels and expiration dates.'),
('Pharmacy & Treatment', 'Drug Interaction Awareness', 'Recognizing contraindications between prescribed meds.'),
('Pharmacy & Treatment', 'Pharmacy Label Accuracy', 'Ensuring client labels meet legal and safety standards.'),
('Pharmacy & Treatment', 'Refill Authorization Workflow', 'Process for reviewing and approving prescription requests.'),

-- Specialty Skills
('Specialty Skills', 'Cardiology Diagnostics', 'Assisting with echocardiograms and Holter monitors.'),
('Specialty Skills', 'Ophthalmology Diagnostics', 'Tonometry, tear tests, and stain tests for eyes.'),
('Specialty Skills', 'Exotic Animal Care', 'Husbandry and medical care for non-traditional pets.'),
('Specialty Skills', 'Avian Handling', 'Safe restraint and capture of birds.'),
('Specialty Skills', 'Reptile Handling', 'Safe restraint of lizards, snakes, and chelonians.'),
('Specialty Skills', 'Small Mammal Care', 'Care for rabbits, ferrets, and pocket pets.'),
('Specialty Skills', 'Specialty Surgery Assistance', 'Assisting in orthopedics or soft tissue specialty cases.'),
('Specialty Skills', 'Teleconsultation Support', 'Facilitating remote consults with specialists.'),
('Specialty Skills', 'Advanced Ultrasound', 'Detailed organ scanning beyond A-FAST/T-FAST.'),
('Specialty Skills', 'Endoscopy Support', 'Setting up and maintaining scoping equipment.'),
('Specialty Skills', 'Chemotherapy Protocols', 'Safe handling and administration of cytotoxic drugs.'),

-- Client Service
('Client Service', 'Phone Communication', 'Professional etiquette and clarity on calls.'),
('Client Service', 'Call Control', 'Managing conversation flow and duration effectively.'),
('Client Service', 'Client Empathy', 'Demonstrating understanding of client emotions.'),
('Client Service', 'De-escalation', 'Calming upset clients to resolve conflict.'),
('Client Service', 'Service Recovery', 'Turning a negative experience into a positive one.'),
('Client Service', 'Estimate Presentation', 'Explaining costs and value to clients clearly.'),
('Client Service', 'Financial Conversations', 'Discussing payment options and budget constraints.'),
('Client Service', 'Scheduling Optimization', 'Booking appointments to maximize clinic flow.'),
('Client Service', 'Conflict Diffusion', 'Resolving interpersonal issues between parties.'),
('Client Service', 'Client Education', 'Teaching owners about pet health and care.'),
('Client Service', 'Medical Triage (CSR Level)', 'Determining urgency of phone inquiries.'),
('Client Service', 'Queue Management', 'Managing lobby flow and waiting clients.'),
('Client Service', 'CRM Accuracy', 'Keeping client contact info and notes updated.'),
('Client Service', 'SMS/Chat Support', 'Professional communication via text channels.'),
('Client Service', 'Remote Support Tools', 'Using software to assist clients off-site.'),
('Client Service', 'Referral Coordination', 'Managing records between general and specialty practices.'),
('Client Service', 'NPS Influence', 'Actions that drive positive Net Promoter Scores.'),
('Client Service', 'Multi-tasking Under Pressure', 'Handling phones, lobby, and admin simultaneously.'),
('Client Service', 'Upselling Preventatives', 'Encouraging compliance with flea/tick/heartworm prevention.'),

-- Operations & Admin
('Operations & Admin', 'Appointment Forecasting', 'Predicting future schedule volume and needs.'),
('Operations & Admin', 'Workload Balancing', 'Distributing tasks evenly across the team.'),
('Operations & Admin', 'PIMS Administration', 'Managing settings in Practice Information Management System.'),
('Operations & Admin', 'Record Accuracy', 'Auditing files for completeness.'),
('Operations & Admin', 'Inventory Logging', 'Tracking goods received and usage.'),
('Operations & Admin', 'Email Communication', 'Professional internal and external email correspondence.'),
('Operations & Admin', 'Policy Compliance', 'Adhering to hospital handbook and rules.'),
('Operations & Admin', 'Office Workflow Design', 'Creating efficient administrative processes.'),
('Operations & Admin', 'Report Generation', 'Pulling data reports from practice software.'),
('Operations & Admin', 'Data Entry Accuracy', 'Error-free input of clinical or financial data.'),
('Operations & Admin', 'Clinic Flow Optimization', 'Improving the movement of patients and staff.'),
('Operations & Admin', 'Vendor Communication', 'Managing relationships with suppliers.'),
('Operations & Admin', 'Estimate Auditing', 'Checking invoices against estimates for accuracy.'),
('Operations & Admin', 'Task Delegation', 'Assigning appropriate duties to team members.'),
('Operations & Admin', 'Time Blocking', 'Dedicating time slots to specific focus work.'),
('Operations & Admin', 'Process Documentation', 'Writing SOPs and guides for tasks.'),

-- HR / People Ops
('HR / People Ops', 'Interviewing', 'Conducting effective candidate interviews.'),
('HR / People Ops', 'Candidate Screening', 'Reviewing resumes and applications.'),
('HR / People Ops', 'Culture Stewardship', 'Promoting positive hospital values and morale.'),
('HR / People Ops', 'Onboarding', 'Integrating new hires into the team.'),
('HR / People Ops', 'Training Delivery', 'Teaching skills and protocols to staff.'),
('HR / People Ops', 'Conflict Resolution', 'Mediating disputes between employees.'),
('HR / People Ops', 'Performance Coaching', 'Guiding employees to improve work output.'),
('HR / People Ops', 'Difficult Conversations', 'Addressing behavioral or performance issues directly.'),
('HR / People Ops', 'Employment Law Basics', 'Understanding wage, hour, and labor regulations.'),
('HR / People Ops', 'Scheduling Fairness', 'Creating equitable work rosters.'),
('HR / People Ops', 'Coverage Planning', 'Ensuring adequate staffing for all shifts.'),
('HR / People Ops', 'Retention Strategies', 'Programs to keep staff engaged and employed.'),
('HR / People Ops', 'CE Tracking', 'Monitoring Continuing Education compliance.'),
('HR / People Ops', 'Recognition Practices', 'Rewarding and acknowledging staff achievements.'),
('HR / People Ops', 'Burnout Detection', 'Identifying signs of compassion fatigue in staff.'),
('HR / People Ops', 'Team Engagement', 'Facilitating participation and enthusiasm.'),

-- Practice Management
('Practice Management', 'KPI Interpretation', 'Analyzing Key Performance Indicators for business health.'),
('Practice Management', 'Budget Management', 'Overseeing departmental spending and limits.'),
('Practice Management', 'Revenue Forecasting', 'Projecting future income based on trends.'),
('Practice Management', 'Production/ProSal Modeling', 'Managing doctor compensation structures.'),
('Practice Management', 'Staff Allocation', 'Optimizing labor hours to patient volume.'),
('Practice Management', 'Cost Control', 'Reducing waste and unnecessary expenses.'),
('Practice Management', 'Clinic Workflow Design', 'Architecting the patient journey from check-in to out.'),
('Practice Management', 'Risk Management', 'Identifying and mitigating liability issues.'),
('Practice Management', 'Compliance Oversight', 'Ensuring adherence to all legal regulations.'),
('Practice Management', 'Quality Assurance', 'Monitoring standard of care and service.'),
('Practice Management', 'Vendor Negotiation', 'Bargaining for better pricing or terms.'),
('Practice Management', 'Inventory Cost Control', 'Managing COGS (Cost of Goods Sold).'),
('Practice Management', 'Cash Flow Awareness', 'Monitoring liquidity and operational funds.'),
('Practice Management', 'Strategic Planning', 'Setting long-term business goals.'),
('Practice Management', 'Operational Auditing', 'Reviewing systems for efficiency gaps.'),
('Practice Management', 'Cross-Department Coordination', 'Aligning medical, admin, and kennel teams.'),

-- Training & Education
('Training & Education', 'SOP Creation', 'Writing Standard Operating Procedures.'),
('Training & Education', 'Curriculum Development', 'Designing educational programs for staff.'),
('Training & Education', 'Coaching', 'One-on-one mentorship for skill improvement.'),
('Training & Education', 'Medical Knowledge Instruction', 'Teaching clinical concepts to the team.'),
('Training & Education', 'Shadowing Programs', 'Managing observation periods for trainees.'),
('Training & Education', 'Skills Evaluation', 'Testing and verifying practical competencies.'),
('Training & Education', 'Training Needs Assessment', 'Identifying gaps in team knowledge.'),
('Training & Education', 'CE Program Planning', 'Organizing continuing education events.'),
('Training & Education', 'Mentorship', 'Long-term career guidance for junior staff.'),
('Training & Education', 'Feedback Delivery', 'Providing constructive critique effectively.'),
('Training & Education', 'On-the-Job Training', 'Teaching skills during live clinical work.'),
('Training & Education', 'Performance Tracking', 'Monitoring growth and milestones over time.'),

-- Leadership Skills
('Leadership Skills', 'Strategic Decision-Making', 'Making choices that align with long-term goals.'),
('Leadership Skills', 'Crisis Management', 'Leading effectively during emergencies.'),
('Leadership Skills', 'Team Motivation', 'Inspiring staff to perform their best.'),
('Leadership Skills', 'Delegation', 'Trusting others with responsibility.'),
('Leadership Skills', 'Leadership Communication', 'Conveying vision and instruction clearly.'),
('Leadership Skills', 'Policy Creation', 'Drafting rules and guidelines for the practice.'),
('Leadership Skills', 'Change Management', 'Guiding the team through transitions.'),
('Leadership Skills', 'Goal Setting', 'Defining clear, achievable objectives.'),
('Leadership Skills', 'Cross-Functional Collaboration', 'Working across different roles and departments.'),
('Leadership Skills', 'Conflict Mediation', 'Resolving disputes between parties.'),
('Leadership Skills', 'Culture Maintenance', 'Upholding the core values of the practice.'),
('Leadership Skills', 'Vision Setting', 'Defining the future direction of the organization.'),
('Leadership Skills', 'Accountability Systems', 'Ensuring standards are met consistently.'),
('Leadership Skills', 'Coaching Direct Reports', 'Developing the skills of immediate subordinates.'),

-- Financial Skills
('Financial Skills', 'Revenue Cycle Management', 'Managing the flow of income from service to payment.'),
('Financial Skills', 'Cost Analysis', 'Breaking down expenses to find savings.'),
('Financial Skills', 'Budget Forecasting', 'Predicting future financial needs.'),
('Financial Skills', 'Pricing Strategy', 'Setting service fees appropriately.'),
('Financial Skills', 'Inventory Cost Modeling', 'Analyzing the financial impact of stock.'),
('Financial Skills', 'Payroll Understanding', 'Knowledge of wage calculations and taxes.'),
('Financial Skills', 'Financial KPIs', 'Tracking profit, loss, and margins.'),
('Financial Skills', 'Margin Optimization', 'Maximizing profit on services and goods.'),
('Financial Skills', 'Financial Reporting', 'Creating and reading P&L statements.'),
('Financial Skills', 'Scenario Planning', 'Preparing for various financial futures.'),
('Financial Skills', 'Capital Allocation', 'Deciding where to invest business funds.'),

-- Inventory Skills
('Inventory Skills', 'Ordering', 'Purchasing stock from suppliers.'),
('Inventory Skills', 'Receiving', 'Verifying incoming shipments against orders.'),
('Inventory Skills', 'Vendor Negotiation', 'Discussing price and terms with reps.'),
('Inventory Skills', 'Stock Rotation', 'Using First-In-First-Out (FIFO) methods.'),
('Inventory Skills', 'Expiration Control', 'Minimizing waste from expired drugs.'),
('Inventory Skills', 'DEA Compliance', 'Strictly following federal drug laws.'),
('Inventory Skills', 'Controlled Drug Tracking', 'Logging every unit of regulated substances.'),
('Inventory Skills', 'Inventory Forecasting', 'Predicting stock needs based on usage.'),
('Inventory Skills', 'Backorder Management', 'Handling supply chain shortages.'),
('Inventory Skills', 'Invoice Reconciliation', 'Matching bills to received goods.'),
('Inventory Skills', 'Storage Optimization', 'Organizing stock for efficiency and safety.'),

-- Facilities Skills
('Facilities Skills', 'Equipment Maintenance', 'Routine care of medical machines.'),
('Facilities Skills', 'Safety Inspections', 'Checking the facility for hazards.'),
('Facilities Skills', 'Clinic Cleanliness Standards', 'Maintaining medical-grade hygiene.'),
('Facilities Skills', 'OSHA Compliance', 'Adhering to workplace safety regulations.'),
('Facilities Skills', 'Biohazard Handling', 'Proper disposal of medical waste.'),
('Facilities Skills', 'Chemical Safety', 'Safe storage and use of cleaning agents.'),
('Facilities Skills', 'Vendor Scheduling', 'Coordinating repairs and services.'),
('Facilities Skills', 'Emergency Preparedness', 'Readiness for fire, flood, or power loss.'),
('Facilities Skills', 'Environmental Control', 'Managing temperature, ventilation, and noise.'),

-- Technology Skills
('Technology Skills', 'PIMS Mastery', 'Expert use of practice management software.'),
('Technology Skills', 'Telemedicine Tools', 'Operating video consult platforms.'),
('Technology Skills', 'Remote CSR Systems', 'Using VOIP and remote desktop tools.'),
('Technology Skills', 'Data Entry Mastery', 'Fast and accurate typing and input.'),
('Technology Skills', 'Reporting Dashboards', 'Using analytics tools to view metrics.'),
('Technology Skills', 'Cloud File Management', 'Organizing documents in Google Drive/Dropbox.'),
('Technology Skills', 'Troubleshooting', 'Basic fixing of IT issues.'),
('Technology Skills', 'Digital Payments', 'Processing credit cards and online transactions.'),
('Technology Skills', 'Workflow Software', 'Using project management tools (Asana, etc.).'),
('Technology Skills', 'Cybersecurity Basics', 'Awareness of phishing and password safety.'),
('Technology Skills', 'Device Setup', 'Configuring tablets, printers, and scanners.'),

-- Soft Skills
('Soft Skills', 'Communication', 'Exchanging information clearly and effectively.'),
('Soft Skills', 'Empathy', 'Understanding and sharing feelings of others.'),
('Soft Skills', 'Problem Solving', 'Finding solutions to difficult issues.'),
('Soft Skills', 'Adaptability', 'Adjusting easily to new conditions.'),
('Soft Skills', 'Time Management', 'Using work hours productively.'),
('Soft Skills', 'Teamwork', 'Working collaboratively with a group.'),
('Soft Skills', 'Professionalism', 'Maintaining high standards of behavior.'),
('Soft Skills', 'Ownership', 'Taking responsibility for outcomes.'),
('Soft Skills', 'Initiative', 'Taking action without being told.'),
('Soft Skills', 'Emotional Regulation', 'Managing one''s own emotional state.'),
('Soft Skills', 'Stress Tolerance', 'Maintaining performance under pressure.'),
('Soft Skills', 'Critical Thinking', 'Objective analysis to form a judgment.'),
('Soft Skills', 'Attention to Detail', 'Accuracy in small particulars.'),
('Soft Skills', 'Reliability', 'Being dependable and consistent.'),
('Soft Skills', 'Resilience', 'Recovering quickly from difficulties.'),
('Soft Skills', 'Creative Thinking', 'Thinking outside traditional methods.'),
('Soft Skills', 'Accountability', 'Being answerable for actions.'),

-- Gameplay Attributes
('Gameplay Attributes', 'Medical Competency', 'Overall rating of clinical knowledge.'),
('Gameplay Attributes', 'Efficiency', 'Speed of task completion without error.'),
('Gameplay Attributes', 'Accuracy', 'Precision in medical and admin tasks.'),
('Gameplay Attributes', 'Autonomy', 'Ability to work without supervision.'),
('Gameplay Attributes', 'Stress Resistance', 'Ability to maintain performance under pressure.'),
('Gameplay Attributes', 'Recovery Rate', 'Speed of bouncing back from difficult shifts.'),
('Gameplay Attributes', 'Compassion Fatigue Sensitivity', 'Vulnerability to emotional burnout.'),
('Gameplay Attributes', 'Morale', 'Current level of job satisfaction and enthusiasm.'),
('Gameplay Attributes', 'Team Synergy', 'Effectiveness of working within this specific group.'),
('Gameplay Attributes', 'Leadership Trust', 'Confidence in the management team.'),
('Gameplay Attributes', 'Engagement', 'Level of active participation in the role.'),
('Gameplay Attributes', 'Production Contribution', 'Impact on revenue generation.'),
('Gameplay Attributes', 'Client Experience', 'Impact on client satisfaction scores.'),
('Gameplay Attributes', 'Specialty Bonus – Surgery', 'Performance buff in surgical environments.'),
('Gameplay Attributes', 'Specialty Bonus – Dentistry', 'Performance buff in dental environments.'),
('Gameplay Attributes', 'Specialty Bonus – Emergency', 'Performance buff in ER environments.'),

-- Creative / Marketing
('Creative / Marketing', 'Content Writing', 'Creating text for blogs or social media.'),
('Creative / Marketing', 'Blog Writing', 'Writing long-form educational articles.'),
('Creative / Marketing', 'Graphic Design', 'Creating visual assets for marketing.'),
('Creative / Marketing', 'Brand Messaging', 'Maintaining consistent voice and tone.'),
('Creative / Marketing', 'Social Media Strategy', 'Planning posts to maximize engagement.'),
('Creative / Marketing', 'Community Engagement', 'Interacting with followers online.'),
('Creative / Marketing', 'Video Editing', 'Cutting and polishing video content.'),
('Creative / Marketing', 'Marketing Analytics', 'Interpreting campaign performance data.'),
('Creative / Marketing', 'Campaign Execution', 'Rolling out marketing initiatives.'),
('Creative / Marketing', 'Educational Content Creation', 'Making materials to teach clients.'),

-- Legal / Compliance
('Legal / Compliance', 'Regulatory Knowledge', 'Understanding veterinary laws.'),
('Legal / Compliance', 'Contract Review', 'Analyzing legal agreements.'),
('Legal / Compliance', 'Policy Development', 'Writing compliant workplace rules.'),
('Legal / Compliance', 'Legal Risk Awareness', 'Identifying potential lawsuit triggers.'),
('Legal / Compliance', 'Documentation Compliance', 'Ensuring records meet legal standards.'),
('Legal / Compliance', 'Medical Record Standards', 'Maintaining complete patient files.'),
('Legal / Compliance', 'Privacy Compliance', 'Protecting client and employee data.'),

-- Remote Work Skills
('Remote Work Skills', 'Remote Communication', 'Staying connected while off-site.'),
('Remote Work Skills', 'Self-Management', 'Working effectively without oversight.'),
('Remote Work Skills', 'Asynchronous Collaboration', 'Working on shared projects at different times.'),
('Remote Work Skills', 'Virtual Teamwork', 'Building rapport digitally.'),
('Remote Work Skills', 'Remote Workspace Setup', 'Creating an effective home office.'),
('Remote Work Skills', 'Queue Management', 'Handling digital waiting lines.'),
('Remote Work Skills', 'Digital Empathy', 'Conveying care through text/video.'),
('Remote Work Skills', 'Independent Problem Solving', 'Troubleshooting without immediate help.'),
('Remote Work Skills', 'Remote Productivity Systems', 'Using tools to track and maintain output.');
