-- =====================================================
-- Pet Related Businesses Import
-- Imported from: GDD Referral Master Lists - PET RELATED BUSINESS LIST.pdf
-- Total businesses: 196
-- =====================================================

INSERT INTO marketing_partners (name, partner_type, status, contact_phone, contact_email, address, services_provided, notes)
VALUES
  ('C& C Pet Food For Less', 'pet_business', 'prospect', '(818) 830-1452', NULL, NULL, 'Retail', 'Zone: AETNA; 3/25'),
  ('Erick''''s Pet Grooming', 'pet_business', 'prospect', '(818) 492-6479', NULL, NULL, 'Groomer', 'Zone: AETNA; 3/25'),
  ('Pup without Borders', 'rescue', 'prospect', '(213) 513-7672', NULL, NULL, 'Dog Shelter/Rescue', 'Zone: AETNA; 3/25'),
  ('Los Angeles City East Valley Animal Shelter', 'rescue', 'prospect', '(888) 452-7381', NULL, NULL, 'Dog Shelter/Rescue', 'Zone: SO; 3/25'),
  ('Petco', 'pet_business', 'prospect', '(818) 997-4009', NULL, NULL, 'Retail', 'Zone: AETNA; 3/25'),
  ('Dig it Pet Supplies', 'pet_business', 'prospect', '(818) 904-3331', NULL, NULL, 'Retail', 'Zone: AETNA; 3/25'),
  ('Happiness Grooming', 'pet_business', 'prospect', '(818) 387-8279', NULL, NULL, 'Groomer', 'Zone: AETNA; 3/25'),
  ('AJ''''s Pet Shop & Grooming', 'pet_business', 'prospect', '(818) 906-7387', 'zajpetgrooming@gmail.com', NULL, 'Groomer, Retail', 'Zone: AETNA; 3/25'),
  ('Lazyboy Pet Store', 'pet_business', 'prospect', '(818) 849-1524', NULL, NULL, 'Retail', 'Zone: AETNA; 3/25'),
  ('Wash My Dog Van Nuys LLC', 'pet_business', 'prospect', '(818) 616-9288', NULL, NULL, 'Groomer, Daycare', 'Zone: AETNA; Priority: HIGH; 3/25'),
  ('Animal of World- Foundation', 'rescue', 'prospect', '(626) 255-0818', NULL, NULL, 'Dog Shelter/Rescue', 'Zone: AETNA; 3/25'),
  ('Pet Orphans of Southern California', 'rescue', 'prospect', '(818) 901-0190', NULL, NULL, 'Dog Shelter/Rescue', 'Zone: AETNA; Priority: HIGH; 3/25'),
  ('Delayney''''s Dogs Rescue & Adoption', 'rescue', 'prospect', '(818) 300-6002', NULL, NULL, 'Dog Shelter/Rescue', 'Zone: AETNA; 3/25'),
  ('Art Vark Pet Product Inc', 'pet_business', 'prospect', '(818) 904-2529', 'info@artvarkpet.com', NULL, 'Retail', 'Zone: AETNA; 3/25'),
  ('Blue Diamond Pets', 'pet_business', 'prospect', '(818) 231-4801', NULL, NULL, 'Groomer', 'Zone: AETNA; 3/25'),
  ('California Cat Center', 'pet_business', 'prospect', '(818) 780-7060', 'californiacatcenter@gmail.com', NULL, 'Hotel', 'Zone: AETNA; 3/25'),
  ('Biju Pet Spa', 'pet_business', 'prospect', '(818) 990-7387', 'bijupetspa@gmail.com4528', NULL, 'Groomer', 'Zone: SO; 3/26'),
  ('The Groom Room', 'pet_business', 'prospect', '(323) 286-6372', NULL, NULL, 'Groomer', 'Zone: AETNA; 3/26'),
  ('PetsSmart', 'pet_business', 'prospect', '(818) 742-1753', NULL, NULL, 'Retail', 'Zone: AETNA; 3/26'),
  ('Pride''''n Joy Pet Care Center', 'pet_business', 'prospect', '(818) 784-6243', NULL, NULL, 'Groomer, Retail', 'Zone: AETNA; 3/26'),
  ('Just Food For Dogs', 'pet_business', 'prospect', '(747) 208-6900', NULL, NULL, 'Retail', 'Zone: AETNA; 3/26'),
  ('PAW REHAB Pacific Animal Wellness Rehabilitation Center', 'other', 'prospect', '(818) 847-7299', 'info@pawrehab.com', NULL, 'Other', 'Zone: AETNA; Priority: HIGH; 3/26'),
  ('Dog-E-Den Dog Daycare Boarding', 'pet_business', 'prospect', '(818) 784-8408', 'info@dog-e-den.com', NULL, 'Groomer, Daycare', 'Zone: AETNA; 3/26'),
  ('K9 Loft', 'pet_business', 'prospect', '(818) 905-6006', NULL, NULL, 'Retail, Groomer, Daycare', 'Zone: AETNA; Priority: HIGH; 3/26'),
  ('Hounds of the Hills', 'pet_business', 'prospect', '(818) 396-8623', 'houndsofthehills2@gmail.com', NULL, 'Daycare', 'Zone: AETNA; 3/26'),
  ('Paw Haven', 'pet_business', 'prospect', '(747) 250-9354', NULL, NULL, 'Groomer, Hotel, Daycare', 'Priority: HIGH; 3/26'),
  ('Wiggles Pet SPA', 'pet_business', 'prospect', '(818) 616-3365', NULL, NULL, 'Groomer', 'Zone: AETNA; 3/26'),
  ('Catington', 'pet_business', 'prospect', '(818) 817-1477', 'meow@catington.com4327', NULL, 'Groomer', 'Zone: SO; 3/26'),
  ('Andy''''s Pet Grooming & Daycare', 'other', 'prospect', '(818) 616-3466', NULL, NULL, 'Other', '3/26'),
  ('Centinela Pet and Feed', 'pet_business', 'prospect', '(818) 990-0744', NULL, NULL, 'Retail', 'Zone: AETNA; Priority: HIGH; 3/26'),
  ('Barkin Groomers', 'pet_business', 'prospect', '(818) 359-0718', NULL, NULL, 'Groomer', 'Zone: AETNA; Priority: POTENTIAL; 3/26'),
  ('Petrock Hotel & Spa', 'pet_business', 'prospect', '(818) 817-9451', 'info@petrockhotel.com17401', NULL, 'Hotel, Daycare, Other', 'Zone: AETNA; Priority: HIGH; 3/26'),
  ('D Pet Hotels Los Angeles (Encino)', 'pet_business', 'prospect', '(818) 392-5305', NULL, NULL, 'Groomer, Hotel, Daycare', 'Zone: AETNA; Priority: HIGH; 3/26'),
  ('Pet Lovers Resort', 'pet_business', 'prospect', '(818) 578-5664', NULL, NULL, 'Hotel', 'Zone: AETNA; 3/26'),
  ('Pet Food Express', 'pet_business', 'prospect', '(818) 342-5566', NULL, NULL, 'Retail, Other', 'Zone: AETNA; 3/26'),
  ('Theresa''''s Country Feed & Pet RedBarn', 'pet_business', 'prospect', '(818) 345-2510', NULL, NULL, 'Retail', 'Zone: AETNA; 3/26'),
  ('Four Paws DayCare', 'other', 'prospect', '(818) 986-5700', 'friends@fourpawsdaycare.com', NULL, 'Other', '3/26'),
  ('Buddy: Canine Wellness', 'other', 'prospect', '(323) 891-4880', 'hello@buddyk9.com', NULL, 'Other', 'Zone: SO; 3/26'),
  ('Village Pet Supply', 'pet_business', 'prospect', '(818) 579-4434', 'info@villagepetsupplyla.com', NULL, 'Retail', 'Zone: AETNA; 3/26'),
  ('Birds Plus', 'pet_business', 'prospect', '(818) 901-1187', NULL, NULL, 'Retail', 'Zone: AETNA; Priority: POTENTIAL; 3/26'),
  ('Creature Comfort Bnb', 'pet_business', 'prospect', '(818) 967-9042', 'creaturecomfortbnb@gmail.com', NULL, 'Daycare, Hotel', 'Zone: AETNA; 3/26'),
  ('Perry''''s Place, Heaven on Earth Adoption Center', 'rescue', 'prospect', '(818) 474-2700', 'info@heavenlypets.org7342', NULL, 'Dog Shelter/Rescue', 'Zone: AETNA; Priority: POTENTIAL; 3/26'),
  ('Euphuria Pet Salon', 'pet_business', 'prospect', '(818) 760-2110', NULL, NULL, 'Groomer', '3/26'),
  ('Tams Pet Foods & Supplies', 'pet_business', 'prospect', '(818) 343-6873', NULL, NULL, 'Retail', 'Zone: AETNA; Priority: POTENTIAL; 3/26'),
  ('Unleashed', 'pet_business', 'prospect', '(310) 577-5215', NULL, NULL, 'Retail', '3/21'),
  ('Echo Bark', 'pet_business', 'prospect', '(323) 660-2275', 'jf@echobarkinc.com', NULL, 'Retail', '3/21'),
  ('For Pets Only', 'pet_business', 'prospect', '(323) 664-4211', NULL, NULL, 'Retail', '3/21'),
  ('PETSAURANT', 'pet_business', 'prospect', '(424) 256-2444', NULL, NULL, 'Retail', '3/21'),
  ('The Dog Bakery', 'pet_business', 'prospect', '(310) 313-1801', NULL, NULL, 'Retail', '3/21'),
  ('Olympic Pet Shop', 'pet_business', 'prospect', '(213) 385-3355', NULL, NULL, 'Groomer, Retail', '3/21'),
  ('California Pet Supplies', 'pet_business', 'prospect', '(310) 804-5234', NULL, NULL, 'Retail', '3/21'),
  ('My Pet''''s Place', 'pet_business', 'prospect', '(323) 934-0780', NULL, NULL, 'Retail', '3/21'),
  ('The Malibu Food Bin', 'pet_business', 'prospect', '(310) 456-2043', NULL, NULL, 'Retail', '3/21'),
  ('Pacific Coast Pets', 'pet_business', 'prospect', '(310) 317-8600', NULL, NULL, 'Retail', '3/21'),
  ('Centinela Feed & Pet Supplies', 'pet_business', 'prospect', '(310) 451-7140', NULL, NULL, 'Retail', '3/21'),
  ('My Pet Naturally', 'pet_business', 'prospect', '(310) 477-3030', NULL, NULL, 'Retail', '3/21'),
  ('Healthy Spot', 'pet_business', 'prospect', '(310) 458-2004', NULL, NULL, 'Retail', '3/21'),
  ('Groovy Pup', 'pet_business', 'prospect', '(310) 752-4649', NULL, NULL, 'Retail', '3/21'),
  ('HAPPYBOND', 'pet_business', 'prospect', '(310) 913-4222', NULL, NULL, 'Retail', '3/21'),
  ('Modern Beast', 'pet_business', 'prospect', '(310) 476-6530', 'madison@modernbeast.com', NULL, 'Retail', '3/21'),
  ('TailWaggers West Hollywood', 'pet_business', 'prospect', '(323) 464-9600', NULL, NULL, 'Retail', '3/21'),
  ('The Urban Pet West Hollywood', 'pet_business', 'prospect', '(323) 952-6088', NULL, NULL, 'Retail', NULL),
  ('Poshpetcare', 'pet_business', 'prospect', '(323) 655-7674', NULL, NULL, 'Retail', '3/18'),
  ('Ball and Bone', 'pet_business', 'prospect', '(310) 734-8879', NULL, NULL, 'Retail', 'YES - by Gladys'),
  ('Allan''''s Pet Center', 'pet_business', 'prospect', '(424) 832-3009', NULL, NULL, 'Retail', 'YES - by Mellisa'),
  ('GREEN GODDESS', 'pet_business', 'prospect', '(844) 420-8442', NULL, NULL, 'Retail', 'YES - by Mellisa'),
  ('STARBUCKS - BOARDWALK', 'pet_business', 'prospect', '(310) 314-7238', NULL, NULL, 'Retail', 'YES - by Mellisa'),
  ('ST. MATHEWS THRIFT SHOP', 'pet_business', 'prospect', '(310) 396-9776', NULL, NULL, 'Retail', 'YES - by Gladys'),
  ('ROSE COLLECTIVE', 'pet_business', 'prospect', '(424) 252-9365', NULL, NULL, 'Retail', 'YES - by Mellisa'),
  ('iHATE THE DESTIST', 'pet_business', 'prospect', '(310) 319-9300', NULL, NULL, 'Retail', 'YES - by Mellisa'),
  ('THE BIKE SHOP - SM', 'pet_business', 'prospect', '(310) 581-8014', NULL, NULL, 'Retail', 'YES - by Mellisa'),
  ('Mr. Specks Daycare & Grooming', 'pet_business', 'prospect', '(323) 746-5636', NULL, NULL, 'Groomer, Daycare, Hotel', 'YES - by Mellisa'),
  ('Wags 2 Whiskers', 'pet_business', 'prospect', '(310) 202-9247', NULL, NULL, 'Daycare', 'YES - by Gladys'),
  ('Dog Resort', 'pet_business', 'prospect', '(323) 499-1414', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Dog-E-Den', 'pet_business', 'prospect', '(323) 647-3491', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('D Pet Hotels', 'pet_business', 'prospect', '(323) 464-7387', NULL, NULL, 'Daycare', 'YES - by Gladys'),
  ('Pawn LA LA', 'pet_business', 'prospect', '(213) 738-7297', 'info@pawlalaclub.com1521', NULL, 'Daycare', 'YES - by Mellisa'),
  ('Chateau Marmutt', 'pet_business', 'prospect', '(323) 653-2062', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Eco Dog Care LA', 'pet_business', 'prospect', '(323) 939-0945', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Sunset Barquis', 'pet_business', 'prospect', '(323) 297-3342', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Happy Doggies Dog Camp/ Day Care', 'pet_business', 'prospect', '(323) 556-4409', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Doggie Goddess Pet Services', 'pet_business', 'prospect', '(323) 919-4798', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('WagVille', 'pet_business', 'prospect', '(323) 222-4442', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('The Ranch Dog Training', 'pet_business', 'prospect', '(310) 742-9988', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Puparrazi La Dog Daycare and Boarding', 'pet_business', 'prospect', '(424) 325-3151', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Country Dog Ranch', 'pet_business', 'prospect', '(800) 591-1080', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('NOT YET', 'pet_business', 'prospect', '(310) 456-8982', NULL, NULL, 'Daycare', NULL),
  ('The Wags Club', 'pet_business', 'prospect', '(310) 473-3333', NULL, NULL, 'Daycare', '3/18'),
  ('Rover Kennels', 'pet_business', 'prospect', '(310) 450-0705', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('FitDog', 'pet_business', 'prospect', '(310) 828-3647', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Lincoln Bark', 'pet_business', 'prospect', '(424) 235-4094', 'info@lincolnbarkpets.com1437', NULL, 'Daycare', 'YES - by Mellisa'),
  ('Fetch Pet Care', 'pet_business', 'prospect', '(310) 577-6137', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Puppy Play Time', 'pet_business', 'prospect', '(310) 448-3488', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Santa Monica Paws', 'pet_business', 'prospect', '(424) 272-1036', 'pets@santamonicapaws.com', NULL, 'Daycare', 'YES - by Mellisa'),
  ('Down Dog Lodge', 'pet_business', 'prospect', '(310) 606-5507', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('The Grateful Dog Clubhouse', 'pet_business', 'prospect', '(310) 364-0011', 'info@gratefuldogs.net202', NULL, 'Daycare', 'YES - by Gladys'),
  ('El Segundo Pet Resort', 'pet_business', 'prospect', '(310) 322-6506', 'elsegundopetresort@gmail.com', NULL, 'Daycare', 'YES - by Gladys'),
  ('Howie''''s Doggy Daycare', 'pet_business', 'prospect', '(310) 322-4150', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Camp Run-A-Mutt LAX', 'pet_business', 'prospect', '(833) 386-2267', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Camp Puppies', 'pet_business', 'prospect', '(925) 200-6620', 'hellocamppuppies@gmail.com', NULL, 'Daycare', 'YES - by Mellisa'),
  ('Venice Dog Boarding and Daycare', 'pet_business', 'prospect', '(213) 270-5578', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Happy Dog Service', 'pet_business', 'prospect', '(310) 463-2641', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Citydog! Club', 'pet_business', 'prospect', '(213) 257-8700', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('STARDOGS Clubhouse', 'pet_business', 'prospect', '(424) 245-4493', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('West LA Dogs', 'pet_business', 'prospect', '(310) 597-0424', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Wag Hotels', 'pet_business', 'prospect', '(888) 924-5463', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('K9''''s Only', 'pet_business', 'prospect', '(424) 901-1701', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Four Paws Daycare West LA', 'pet_business', 'prospect', '(424) 832-7657', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Dog Gone Fitness', 'pet_business', 'prospect', '(310) 435-5078', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('Paw-someDog', 'pet_business', 'prospect', '(424) 293-0312', NULL, NULL, 'Daycare', 'YES - by Mellisa'),
  ('MARINA PET SPA', 'pet_business', 'prospect', '(310) 827-5949', NULL, NULL, 'Daycare, Groomer', 'YES - by Mellisa'),
  ('mobile pet spa', 'pet_business', 'prospect', '(818) 755-7900', 'staff@groomersonwheels.com', NULL, 'Groomer', 'YES - by Mellisa'),
  ('Pet Joy Boutique and Spa', 'pet_business', 'prospect', '(310) 471-0088', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Pet Wash', 'pet_business', 'prospect', '(323) 882-6855', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Angie''''s Pooch Pawlor', 'pet_business', 'prospect', '(323) 645-7475', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('West LA Grooming Academy', 'pet_business', 'prospect', '(310) 461-2364', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Jose Diego''''s Dog Grooming', 'pet_business', 'prospect', '(310) 821-3364', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Precious Paws Grooming', 'pet_business', 'prospect', '(310) 482-3240', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Tender Loving Care Pet Spa', 'pet_business', 'prospect', '(310) 479-4319', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Bubbles Dog Grooming', 'pet_business', 'prospect', '(213) 736-0068', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Lucky Dog Grooming Co', 'pet_business', 'prospect', '(310) 479-5552', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Melrose Pet Grooming', 'pet_business', 'prospect', '(323) 993-1959', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Jungle Pet Spa Mobile Grooming', 'pet_business', 'prospect', '(310) 654-6910', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Alex the Happy Dog', 'pet_business', 'prospect', '(323) 933-9708', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('WOWOW', 'pet_business', 'prospect', '(323) 739-6856', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('BarkBus Mobile Pet Grooming', 'pet_business', 'prospect', '(818) 964-1024', NULL, NULL, 'Groomer', 'YES - by Gladys'),
  ('April''''s Furry Tail Moblie Pet Grooming', 'pet_business', 'prospect', '(323) 214-6965', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Hollywood Grooming', 'pet_business', 'prospect', '(310) 476-3353', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Mabel''''s Moblie Grooming', 'pet_business', 'prospect', '(310) 440-9495', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('K9 Grooming Mobile Pet Salon', 'pet_business', 'prospect', '(310) 479-0394', 'contact@k9groomingla.com2114', NULL, 'Groomer', 'YES - by Mellisa'),
  ('Button Nose Pet shop', 'pet_business', 'prospect', '(818) 864-6655', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Murphy''''s Mobile Pet Services', 'pet_business', 'prospect', '(310) 457-6273', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Refresh Pet Salon', 'pet_business', 'prospect', '(310) 457-6453', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Splish Splash Mobile Pet Grooming', 'pet_business', 'prospect', '(310) 804-0092', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Malibu Grooming Company', 'pet_business', 'prospect', '(310) 456-6088', 'malibugroomingco@aol.com', NULL, 'Groomer', 'YES - by Mellisa'),
  ('Balanced. Dog Grooming', 'pet_business', 'prospect', '(310) 359-8455', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('A Cut Above', 'pet_business', 'prospect', '(818) 949-2673', 'linda@cutabovegrooming.com', NULL, 'Groomer', 'YES - by Mellisa'),
  ('Paws N Claws Grooming Salon', 'pet_business', 'prospect', '(310) 459-2009', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Bens Mobile Dog Spa LLC', 'pet_business', 'prospect', '(310) 968-2782', NULL, NULL, 'Groomer', 'YES - by Mellisa'),
  ('Seaside Grooming', 'pet_business', 'prospect', '(310) 823-7798', NULL, NULL, 'Groomer', NULL),
  ('Moon Shine Grooming & Pet Wash', 'pet_business', 'prospect', '(323) 664-4600', NULL, NULL, 'Groomer', NULL),
  ('Tailwaggers & Tailwashers', 'pet_business', 'prospect', '(323) 464-9600', NULL, NULL, 'Groomer', NULL),
  ('Moon Doggy''''s Grooming', 'pet_business', 'prospect', '(310) 396-3865', NULL, NULL, 'Groomer', NULL),
  ('The Pet Affair', 'pet_business', 'prospect', '(310) 396-0804', NULL, NULL, 'Groomer', NULL),
  ('Paws and Effect Pet Spa', 'pet_business', 'prospect', '(310) 450-9017', NULL, NULL, 'Groomer', 'Zone: VENICE; Priority: HIGH'),
  ('Animal Kingdom of Santa Monica', 'pet_business', 'prospect', '(310) 392-4074', NULL, NULL, 'Groomer', NULL),
  ('Yo Dawg Groom Spot', 'pet_business', 'prospect', '(310) 450-2090', NULL, NULL, 'Groomer', NULL),
  ('Lucky''''s Pet Care', 'pet_business', 'prospect', '(310) 582-8800', 'luckyspetgrooming@gmail.com', NULL, 'Groomer', NULL),
  ('To Wag for Boutique and grooming', 'pet_business', 'prospect', '(310) 656-9663', NULL, NULL, 'Groomer', NULL),
  ('Bark Williams', 'pet_business', 'prospect', '(310) 664-7009', NULL, NULL, 'Groomer', NULL),
  ('Kriser''''s Natural Pet', 'pet_business', 'prospect', '(424) 744-8329', NULL, NULL, 'Groomer', NULL),
  ('Bruno''''s Cat and Dog Boutique', 'pet_business', 'prospect', '(424) 268-4031', NULL, NULL, 'Groomer', NULL),
  ('Collar and Comb', 'pet_business', 'prospect', '(323) 688-2275', NULL, NULL, 'Groomer', NULL),
  ('Groom - Dog Care with Love', 'pet_business', 'prospect', '(310) 492-5222', NULL, NULL, 'Groomer', NULL),
  ('Orange Bone', 'pet_business', 'prospect', '(323) 852-1258', NULL, NULL, 'Groomer', NULL),
  ('Dogue Spa', 'pet_business', 'prospect', '(424) 303-2027', NULL, NULL, 'Groomer', NULL),
  ('Rock Star Rover', 'pet_business', 'prospect', '(323) 656-7625', 'rockstarrover@yahoo.com', NULL, 'Groomer', NULL),
  ('Blue Pooch Grooming', 'pet_business', 'prospect', '(310) 473-4173', NULL, NULL, 'Groomer', NULL),
  ('Pamered Tails', 'pet_business', 'prospect', '(800) 978-2457', NULL, NULL, 'Groomer', NULL),
  ('Sparky''''s', 'pet_business', 'prospect', '(310) 909-7423', NULL, NULL, 'Groomer', NULL),
  ('Westside Pet Stop', 'pet_business', 'prospect', '(310) 202-1076', NULL, NULL, 'Groomer', NULL),
  ('BALANCED DOG GROOMING', 'pet_business', 'prospect', '(310) 384-6162', NULL, 'Via Marina, Marina Del Rey, CA 90292', 'Groomer', 'Zone: VENICE; Priority: HIGH'),
  ('DOGROMAT', 'pet_business', 'prospect', '(310) 306-8885', NULL, NULL, 'Groomer', NULL),
  ('Angels Bark - Dog Rescue', 'other', 'prospect', '9350 Wilshire Blvd. Suite 350, Beverly Hills, CA, United States, California', 'angelsbarkdogrescue@gmail.com', NULL, 'Other', NULL),
  ('Road Dogs & Rescue', 'rescue', 'prospect', '(323) 899-7745', 'info@roaddogsandrescue.org', NULL, 'Dog Shelter/Rescue', NULL),
  ('L.A. Love and Leashes', 'rescue', 'prospect', '(310) 441-1150', NULL, NULL, 'Dog Shelter/Rescue', NULL),
  ('West Side German Shepherd Rescue', 'rescue', 'prospect', '(310) 202-7283', 'info@sheprescue.org', NULL, 'Dog Shelter/Rescue', NULL),
  ('WAGS AND WALKS', 'rescue', 'prospect', '(866) 588-9247', NULL, NULL, 'Dog Shelter/Rescue', NULL),
  ('Perfect Pet Rescue', 'rescue', 'prospect', '(310) 726-3731', NULL, NULL, 'Dog Shelter/Rescue', 'Zone: VENICE'),
  ('Dawg Squad', 'rescue', 'prospect', '(310) 674-0477', 'dawgsquad@rocketmail.com', NULL, 'Dog Shelter/Rescue', 'Zone: VENICE'),
  ('Pacific Pups Rescue', 'rescue', 'prospect', '(310) 614-8222', NULL, NULL, 'Dog Shelter/Rescue', NULL),
  ('Bichons and Buddies', 'rescue', 'prospect', '(310) 398-0237', 'iwngit@gmail.com', NULL, 'Dog Shelter/Rescue', NULL),
  ('St. Francis Animal Center', 'rescue', 'prospect', '(424) 371-9598', NULL, NULL, 'Dog Shelter/Rescue', NULL),
  ('The Labelle Foundation', 'rescue', 'prospect', NULL, 'partnership@labellefoundation.org', 'PO ox 36471 Los Angeles CA 90036', 'Dog Shelter/Rescue', NULL),
  ('The Dog Cafe LA (Permanently Closed)', 'rescue', 'prospect', '(323) 485-4077', 'support@thedogcafela.com240', NULL, 'Dog Shelter/Rescue', NULL),
  ('Barknbitches', 'rescue', 'prospect', NULL, 'shopbnb@gmail.com', NULL, 'Dog Shelter/Rescue', NULL),
  ('Mae Day Rescue', 'rescue', 'prospect', NULL, 'hello@maedayrescue.com', NULL, 'Dog Shelter/Rescue', NULL),
  ('A Purposeful Rescue', 'rescue', 'prospect', '(323) 744-0737', 'apurprescue@yahoo.compo', NULL, 'Dog Shelter/Rescue', NULL),
  ('Dogs Without Borders', 'rescue', 'prospect', NULL, 'info@dogswithoutborders.org', 'PO BOX 17344 Encino, CA 91416', 'Dog Shelter/Rescue', NULL),
  ('I Stand With My Pack', 'rescue', 'prospect', '10736 Jefferson Blvd #273, Culver City CA', 'jazz@iswmp.org', NULL, 'Dog Shelter/Rescue', NULL),
  ('Boomers Buddies Cat/Dog Rescue', 'rescue', 'prospect', NULL, 'boomersbuddiesrescue@gmail.com', 'P.O. Box 29160 Heathcliff Rd #4035 Malibu CA', 'Dog Shelter/Rescue', NULL),
  ('Forte Animal Rescue', 'rescue', 'prospect', '(310) 362-0321', NULL, NULL, 'Dog Shelter/Rescue', NULL),
  ('Love Leo Rescue', 'rescue', 'prospect', NULL, NULL, 'Santa Monica, CA 90409', 'Dog Shelter/Rescue', NULL),
  ('Animal Hope and Wellness', 'rescue', 'prospect', '(747) 998-5568', 'info@animalhopeandwellness.org', NULL, 'Dog Shelter/Rescue', NULL),
  ('Mutt Scouts', 'rescue', 'prospect', NULL, 'themuttscouts@gmail.com325', NULL, 'Dog Shelter/Rescue', NULL),
  ('South LA Animal Shelter', 'rescue', 'prospect', '(888) 452-7381', NULL, NULL, 'Dog Shelter/Rescue', NULL),
  ('Hollywood Huskies', 'rescue', 'prospect', '(310) 467-8116', 'hollywooldhuskiesrescue@gmail.com', NULL, 'Dog Shelter/Rescue', NULL),
  ('Ace of hearts dog rescue', 'rescue', 'prospect', '(310) 358-3344', NULL, NULL, 'Dog Shelter/Rescue', NULL),
  ('West Los Angeles Adoption Center', 'rescue', 'prospect', '(888) 452-7381', NULL, NULL, 'Dog Shelter/Rescue', NULL),
  ('Best Friends West LA Adoption Center (NKLA)', 'rescue', 'prospect', '(424) 208-8840', NULL, NULL, 'Dog Shelter/Rescue', NULL),
  ('Lange Foundation', 'rescue', 'prospect', '(310) 473-5585', NULL, NULL, 'Dog Shelter/Rescue', NULL),
  ('Earthwise', 'pet_business', 'prospect', NULL, NULL, NULL, 'Retail', 'Zone: VENICE; Priority: HIGH'),
  ('Westside Dog Gang', 'other', 'prospect', NULL, NULL, NULL, 'Other', 'Priority: HIGH'),
  ('Alpha One Caine Academy', 'pet_business', 'prospect', NULL, NULL, NULL, 'Trainer', 'Zone: VENICE; Priority: HIGH'),
  ('Bowie Barker', 'pet_business', 'prospect', NULL, NULL, NULL, 'Groomer, Retail', 'Zone: VENICE; Priority: HIGH'),
  ('FixNation', 'rescue', 'prospect', '(818) 298-2065', 'karn@fixnation.org', NULL, 'Dog Shelter/Rescue', 'Priority: HIGH');
