-- Remove animal breed / species "National ... Day" events from marketing_events
-- These are pet-breed-specific and animal-species-specific awareness days
-- that clutter the marketing calendar without business value.

DELETE FROM marketing_events
WHERE name IN (
  'National Bird Day',
  'National Standard Poodle Day',
  'National Alaskan Malamute Day',
  'National Labrador Retriever Day',
  'National Australian Shepherd Day',
  'National French Bulldog Day',
  'National American Eskimo Dog Day',
  'National Boxer Day',
  'National Squirrel Appreciation Day',
  'National Yorkshire Terrier Day',
  'National Serpent Day',
  'National Brown Dog Day',
  'National Hedgehog Day',
  'National Golden Retriever Day',
  'National Boston Terrier Day',
  'National Whippet Day',
  'National Horse Protection Day',
  'National Pig Day',
  'National Welsh Corgi Day',
  'National Panda Day',
  'National Westie Day',
  'National Puppy Day',
  'National Newfoundland Dog Day',
  'National Terrier Day',
  'National Ferret Day',
  'National Siamese Cat Day',
  'National Dolphin Day',
  'National Beagle Day',
  'National Tabby Day',
  'National Greyhound Day',
  'National Dachshund Day',
  'National Cow Appreciation Day',
  'National Kitten Day',
  'National Mutt Day',
  'National Yorkie Day',
  'National Black Cat Appreciation Day',
  'National Dog Day',
  'National White Cat Day',
  'National Iguana Awareness Day',
  'National Black Dog Day',
  'National Feral Cat Day',
  'National Black Cat Day',
  'National Cat Day',
  'National Border Collie Day',
  'National Day of the Horse',
  'National Monkey Day'
)
OR name LIKE 'National Pitbull Awareness Day%';
